name: Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --check

  lint:
    name: Run linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run linting
        run: cargo clippy --no-deps --all-targets --all-features -- --deny warnings

  check-build:
    name: Check build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run build check
        env:
          RUSTFLAGS: "-D warnings"
        run: cargo check --all-targets --all-features

  build-docs:
    name: Build docs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build docs
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps

  run-tests:
    name: Run tests
    runs-on: ubuntu-24.04
    # Just in case something is going to deadlock
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: |
          cargo test --all-targets --all-features
          cargo test --test with-failpoints --features="failpoints/failpoints"
